### ISSUE TITLE
Load in latest emoji

### ISSUE THREAD

**Issue by mscoutermarsh** [producthunt/ShareMeow#12]
![image](https://cloud.githubusercontent.com/assets/155044/21403847/6dafff1a-c773-11e6-8d6e-b1482bbf8261.png)

That blank space should be a 🤖 

I haven't upgraded to macOS Sierra yet. So I can't pull in the newest emojis.

Can someone with Sierra run `bundle exec gemoji extract public/images/emoji` and open a PR?

See gemoji docs here: https://github.com/github/gemoji

This will load in new emoji.

**Comment by jsneedles** [comment]
🤖
